/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinClient

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
      // kotlinClient.main(Array<String>(0) {_ :Int -> ""})
    }
}
