/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinClient

import java.net.*;
import java.io.*;
// import com.github.nkzawa.socketio.client.IO
// import com.github.nkzawa.socketio.client.Socket
// import java.net.URISyntaxException

private const val IP         = "127.0.0.1"
private const val PortNumber = 6969



fun main(args: Array<String>) {
  // Connect
  var socket : Socket = Socket(IP,PortNumber)
  var buf = ByteArray(1024, {_ : Int -> 0})
  // Recive public Key
  socket.getInputStream().read(buf)
  var input = buf.toString(Charsets.UTF_8)
  println("$input")
  // Recive "HELLO"
  socket.getInputStream().read(buf)
  println("Recive $input")
  // Sent "GOODBYE"
  var message = "GOODBYE Γ".toByteArray().toString(Charsets.UTF_8)
  socket.getOutputStream().write(message.toByteArray())
  println("Sending $message")
  // Close connecntion
  socket.close()

}
